[package]
name = "unikko"
version = "0.0.0"
edition = "2021"
description = "Unikko: Poppy"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
